---
 - amazon.aws.ec2_metadata_facts:

 - name: Create certificates folder
   file:
     path: "{{certs_folder}}"
     state: directory
     group: "{{ ansible_user }}"
     owner: "{{ ansible_user }}"

 - name: Generate an OpenSSL private key
   openssl_privatekey:
     path: "{{certs_folder}}/vault.key.pem"
     size: "{{ key_size }}"
     type: "{{ key_type }}"
     backup: yes

 - name: Generate an OpenSSL Certificate Signing Request with Subject information
   openssl_csr:
     path: "{{certs_folder}}/vault.csr.pem"
     privatekey_path: "{{certs_folder}}/vault.key.pem"
     common_name: "{{ansible_ec2_local_hostname}}"
     subject_alt_name: "DNS:*,DNS:*.*,DNS:*.*.*,DNS:{{ansible_ec2_local_hostname}},IP:{{ansible_ec2_local_ipv4}}"

 - name: Generate a Self Signed OpenSSL certificate
   openssl_certificate:
     path: "{{certs_folder}}/vault.crt.pem"
     privatekey_path: "{{certs_folder}}/vault.key.pem"
     csr_path: "{{certs_folder}}/vault.csr.pem"
     selfsigned_not_after: "{{days_valid}}"
     provider: selfsigned

 - name: Delete the CSR file
   file: 
     path: "{{certs_folder}}/vault.csr.pem"
     state: absent
