certs_folder: ./roles/vault/files/
days_valid: "+365d"
key_size: 2048
key_type: RSA # Others include DSA, ECC, Ed25519, Ed448, X25519, X448
#passphrase: # Set if you want passphrase
#country_name: US
#email_address: admin@localhost
#organization_name: localhost
